### ISSUE TITLE
Error using existing packages

### ISSUE THREAD

**Issue by afforeroc** [ibm-cloud-docs/cloud-functions-cli-plugin#15]
Hello everyone, 

I'm trying create and use package bindings
I am running this example:

$ ibmcloud fn package bind /whisk.system/samples valhallaSamples --param place Valhalla
> ok: created binding valhallaSamples

$ ibmcloud fn action invoke --result valhallaSamples/greeting --param name Odin
> Should output
{
    "payload": "Hello, Odin from Valhalla!"
}

...But really prints
{
    "payload": "Hello, Odin from KOL!"
}

These is a error for me, according with course of cognitive class: Serverless Computing using Cloud Functions - Developer I
In Module 3 -> Manage actions with packages -> Use existing packages -> Use existing packages

https://courses.cognitiveclass.ai/courses/course-v1:IBMDeveloperSkillsNetwork+CC0210EN+2020_T2/course/

Thanks, I really want to learn!

**Comment by kersten1** [comment]
Hello! Sorry for the delay but the link that you provided isn't really in my documentation set. However, I was curious so I tried the example that you provided and received the same output that you did. I lodged a question with development and will let you know the answer.

**Comment by kersten1** [comment]
Referred this on to the dev team. Nothing else to do here.

**Comment by afforeroc** [comment]
What was the solution?

**Comment by kersten1** [comment]
Wow - that is bad of me. The issue seems to be isolated to the Dallas region (assuming you are targeting us-south?) I've forwarded the issue to dev, but I am not sure when it will be fixed.
