### ISSUE TITLE
why isn't it working

### ISSUE THREAD

**Issue by SLR1993** [ibm-cloud-docs/cloud-functions-cli-plugin#16]
$(eval a=decodeURIComponent($(querystring)).split( ).map(a=>parseInt(a)).filter(a=>!isNaN(a));a.length==2&&a[1]>=a[0]?Math.floor(Math.random()(a[1]-a[0]+1))+a[0]:Math.ceil(Math.random()100))

**Comment by kersten1** [comment]
@SLR1993 Not sure what you are trying to do here. You do know that this is the Functions cli repo, yes? Can you please reference a page or give more details?
